import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { sobolevStepSet } from '../../src/core/optimizer';
import {
    assertValidConstraintSet,
    barycenterBlock,
    type ConstraintSet,
    edgeLengths,
    edgeLengthsBlock,
    evaluateConstraintSet,
    pointBlock,
    totalLength,
} from '../../src/core/sobolev/constraintSet';
import { barycenterTarget } from '../../src/core/sobolev/constraints';
import { solveConstrainedGradientSet } from '../../src/core/sobolev/gradient';
import { flatten } from '../../src/core/sobolev/layout';
import { lineSearchStepSet } from '../../src/core/sobolev/lineSearch';
import { calculateDisjointPairs, calculateEnergy } from '../../src/core/tangentPointEnergy';
import type { Edge, Vec3 } from '../../src/core/testConfigs';

// The four constraints-M2 golden pairs (spec §5.4.2): per-edge lengths on
// crossing + junction-y (the junction exercises shared-vertex accumulation),
// point pin on crossing + linked-rings. Generated by
// oracle/tpe_constraints_oracle.py modes 'edgelengths'/'point' — the stage-1
// and M1 goldens are never touched.
// @see oracle/README.md ("Constraints goldens")
// @see docs/superpowers/specs/2026-07-03-sobolev-constraints-design.md §5.2, §5.4

// Mirrored line-search tunable, used only to re-verify Armijo from RETURNED
// numbers. OUR constant, not the paper's.
// @see local_files/2026-07-02-sobolev-formula-audit.md (Item 9)
const ARMIJO_C1 = 1e-4;

interface Fixture {
    name: string;
    vertices: Vec3[];
    edges: Edge[];
    alpha: number;
    beta: number;
    epsilon: number;
}

interface GoldenStep {
    accepted: boolean;
    tau: number;
    energy_before: number;
    energy_after: number;
    slope: number;
    gradient_l2_norm: number;
    vertices: Vec3[];
    projection_iterations: number;
    projection_phi_norm: number;
}

interface GoldenM2Base {
    dE: Vec3[];
    x0_barycenter_target: Vec3;
    g_tilde: Vec3[];
    g_tilde_flat: number[];
    lambda: number[];
    line_search_step: GoldenStep;
}

interface GoldenEdgeLengths extends GoldenM2Base {
    ell0_edge_length_targets: number[];
}

interface GoldenPoint extends GoldenM2Base {
    pin_vertex_index: number;
    pin_target: Vec3;
}

// Load at runtime (avoids needing resolveJsonModule in tsconfig; test/** is
// typechecked), mirroring test/sobolev/constraintSetFlow.test.ts.
function loadFixture(name: string): Fixture {
    return JSON.parse(
        readFileSync(new URL(`../../oracle/fixtures/${name}.json`, import.meta.url), 'utf8'),
    ) as Fixture;
}

function loadGolden<T>(basename: string): T {
    return JSON.parse(
        readFileSync(new URL(`../../oracle/golden/${basename}.json`, import.meta.url), 'utf8'),
    ) as T;
}

function euclideanNorm(a: number[]): number {
    let sumSq = 0;
    for (const x of a) sumSq += x * x;
    return Math.sqrt(sumSq);
}

function euclideanDiff(a: number[], b: number[]): number {
    let sumSq = 0;
    for (let i = 0; i < a.length; i++) {
        const d = a[i] - b[i];
        sumSq += d * d;
    }
    return Math.sqrt(sumSq);
}

function matVec(M: number[][], v: number[]): number[] {
    return M.map((row) => row.reduce((s, x, j) => s + x * v[j], 0));
}

function dot(a: number[], b: number[]): number {
    let s = 0;
    for (let i = 0; i < a.length; i++) s += a[i] * b[i];
    return s;
}

// DESIGN DECISION (preserve): inputs are the oracle's own outputs (golden.dE,
// golden targets), NOT TS-side recomputations — decouples the solve comparison
// from cross-language FD noise. Same rationale as constraintSetFlow.test.ts.
// @see oracle/README.md ("Known tolerance caveats")
function goldenSuite(
    label: string,
    name: string,
    fixture: Fixture,
    golden: GoldenM2Base,
    set: ConstraintSet,
    expectedRows: number,
): void {
    test(`solveConstrainedGradientSet[${label}]: ${name} — matches oracle g̃/λ to 1e-9, residual ≤ 1e-10, descent, C·g̃ ≈ 0`, () => {
        const { vertices, edges, alpha, beta, epsilon } = fixture;
        const disjointPairs = calculateDisjointPairs(edges);

        const { gTilde, lambda, residual } = solveConstrainedGradientSet(
            vertices,
            edges,
            disjointPairs,
            alpha,
            beta,
            epsilon,
            golden.dE,
            set,
        );
        const gFlat = flatten(gTilde);

        const gRelDiff =
            euclideanDiff(gFlat, golden.g_tilde_flat) / euclideanNorm(golden.g_tilde_flat);
        const lambdaRelDiff =
            euclideanDiff(lambda, golden.lambda) / Math.max(1, euclideanNorm(golden.lambda));
        const descentDot = dot(flatten(golden.dE), gFlat);
        const { C } = evaluateConstraintSet(set, vertices, edges);
        const constraintRel = euclideanNorm(matVec(C, gFlat)) / Math.max(1, euclideanNorm(gFlat));

        console.log(
            `[gradientM2:${label}] ${name} (|V| = ${vertices.length}): g̃ rel diff = ${gRelDiff.toExponential(3)}, ` +
                `λ rel diff = ${lambdaRelDiff.toExponential(3)} (k = ${lambda.length}), ` +
                `residual = ${residual.toExponential(3)}, ‖C·g̃‖/max(1,‖g̃‖) = ${constraintRel.toExponential(3)}`,
        );

        expect(lambda.length).toBe(expectedRows);
        expect(gRelDiff).toBeLessThanOrEqual(1e-9);
        expect(lambdaRelDiff).toBeLessThanOrEqual(1e-9);
        // Self-certifying saddle residual — spec §E prop 8.
        expect(residual).toBeLessThanOrEqual(1e-10);
        expect(descentDot).toBeGreaterThan(0);
        expect(constraintRel).toBeLessThanOrEqual(1e-10);
    });

    test(`lineSearchStepSet[${label}]: ${name} — matches oracle acceptance, τ, iterations, energy, vertices`, () => {
        const { vertices, edges, alpha, beta, epsilon } = fixture;
        const disjointPairs = calculateDisjointPairs(edges);
        const gold = golden.line_search_step;

        const result = lineSearchStepSet(
            vertices,
            edges,
            disjointPairs,
            alpha,
            beta,
            epsilon,
            golden.dE,
            golden.g_tilde,
            set,
        );

        const energyRelDiff =
            Math.abs(result.energyAfter - gold.energy_after) / Math.abs(gold.energy_after);
        const vertexRelDiff =
            euclideanDiff(flatten(result.vertices), flatten(gold.vertices)) /
            euclideanNorm(flatten(gold.vertices));

        console.log(
            `[lineSearchM2:${label}] ${name}: accepted = ${result.accepted}, τ = ${result.tau}, ` +
                `projection iterations = ${result.projectionIterations}, ` +
                `E ${result.energyBefore.toExponential(6)} → ${result.energyAfter.toExponential(6)} ` +
                `(rel diff vs oracle = ${energyRelDiff.toExponential(3)}), ` +
                `vertices rel diff = ${vertexRelDiff.toExponential(3)}`,
        );

        expect(gold.accepted).toBe(true);
        expect(result.accepted).toBe(gold.accepted);
        // τ EXACT (powers of two — bit-identical across languages; drift means
        // the accept/reject LOGIC diverged). Same gate as the M1 flow tests.
        expect(result.tau).toBe(gold.tau);
        expect(result.projectionIterations).toBe(gold.projection_iterations);
        expect(energyRelDiff).toBeLessThanOrEqual(1e-12);
        expect(vertexRelDiff).toBeLessThanOrEqual(1e-9);

        // Armijo re-verified from RETURNED numbers — spec §C step 9.
        expect(result.slope).toBeDefined();
        expect(result.energyAfter).toBeLessThanOrEqual(
            result.energyBefore - ARMIJO_C1 * result.tau * (result.slope as number),
        );
    });
}

for (const name of ['crossing', 'junction-y'] as const) {
    const fixture = loadFixture(name);
    const golden = loadGolden<GoldenEdgeLengths>(`${name}-edgelengths`);
    goldenSuite(
        'edgeLengths',
        name,
        fixture,
        golden,
        // Barycenter FIRST — the row-order rule of spec §3.2.
        [
            barycenterBlock(golden.x0_barycenter_target),
            edgeLengthsBlock(golden.ell0_edge_length_targets),
        ],
        3 + fixture.edges.length,
    );
}

for (const name of ['crossing', 'linked-rings'] as const) {
    const fixture = loadFixture(name);
    const golden = loadGolden<GoldenPoint>(`${name}-point`);
    goldenSuite(
        'point',
        name,
        fixture,
        golden,
        [
            barycenterBlock(golden.x0_barycenter_target),
            pointBlock(golden.pin_vertex_index, golden.pin_target),
        ],
        6,
    );
}

function maxEdgeDrift(current: Vec3[], edges: Edge[], ell0: number[]): number {
    const now = edgeLengths(current, edges);
    let worst = 0;
    for (let i = 0; i < now.length; i++) {
        worst = Math.max(worst, Math.abs(now[i] - ell0[i]) / ell0[i]);
    }
    return worst;
}

// Drift bounds below MIRROR the per-block projection stopping rule
// ‖Φ_b‖₂ ≤ 1e-4·scale_b that the default projection enforces (value 1e-4 =
// reference-impl backproj_threshold; rule = spec §3.3). Recomputed here
// independently of the projection internals. The old fixed 1e-8 bounds were
// only satisfiable at the pre-provenance 1e-10 tolerance.
// @see oracle/README.md ("Projection tolerance provenance")
function edgeLengthsRuleBound(current: Vec3[], edges: Edge[]): number {
    // edgeLengths block scale = max(1, L) — see constraintSet.ts.
    return 1e-4 * Math.max(1, totalLength(current, edges));
}

function stackedEdgeDrift(current: Vec3[], edges: Edge[], ell0: number[]): number {
    const now = edgeLengths(current, edges);
    let sq = 0;
    for (let i = 0; i < now.length; i++) {
        const d = now[i] - ell0[i];
        sq += d * d;
    }
    return Math.sqrt(sq);
}

function pointRuleBound(current: Vec3[], target: Vec3): number {
    // point block scale = max(1, R), R = max vertex distance to the target.
    let R = 0;
    for (const p of current) R = Math.max(R, distTo(p, target));
    return 1e-4 * Math.max(1, R);
}

function distTo(p: Vec3, q: Vec3): number {
    return Math.hypot(p[0] - q[0], p[1] - q[1], p[2] - q[2]);
}

// Flow property (spec §5.4.3, oracle-independent): per-edge mode on crossing —
// "isometric untangling": after EVERY step the stacked edge-length drift
// satisfies the projection stopping rule (edgeLengthsRuleBound above), energy
// strictly decreases, all steps accepted.
test('flow: 5 steps on crossing with [barycenter, edgeLengths] — accepted, energy ↓, edge drift within stopping rule each step', () => {
    const { vertices, edges, alpha, beta, epsilon } = loadFixture('crossing');
    const disjointPairs = calculateDisjointPairs(edges);
    // Frozen targets: computed ONCE from the initial state (spec §3.5).
    const x0 = barycenterTarget(vertices, edges);
    const ell0 = edgeLengths(vertices, edges);
    const set: ConstraintSet = [barycenterBlock(x0), edgeLengthsBlock(ell0)];
    const opts = { mode: 'analytical' as const, alpha, beta, epsilon };

    let current = vertices;
    let previousEnergy = calculateEnergy(current, edges, disjointPairs, alpha, beta, epsilon);
    for (let step = 0; step < 5; step++) {
        const r = sobolevStepSet(current, edges, disjointPairs, set, opts);
        expect(r.accepted).toBe(true);
        expect(r.energy).toBeLessThan(previousEnergy);
        current = r.vertices;
        previousEnergy = r.energy;
        const stacked = stackedEdgeDrift(current, edges, ell0);
        const bound = edgeLengthsRuleBound(current, edges);
        console.log(
            `[flowM2:perEdge] step ${step + 1}: τ = ${r.stats.tau}, E = ${r.energy.toExponential(6)}, ` +
                `‖g̃‖ = ${r.stats.gradientL2Norm.toExponential(3)}, ‖ℓ−ℓ⁰‖ = ${stacked.toExponential(3)} ` +
                `(bound ${bound.toExponential(3)}, max per-edge rel ${maxEdgeDrift(current, edges, ell0).toExponential(3)})`,
        );
        expect(stacked).toBeLessThanOrEqual(bound);
    }
});

// Point flow (spec §5.4.5): pin vertex 0 on crossing, 3 steps — γ₀ within the
// stopping-rule bound (pointRuleBound above) of the target after every step
// while energy decreases. The pin-only set also exercises a barycenter-less
// ConstraintSet (spec §9a).
test('flow: 3 steps on crossing with [point(0)] — accepted, energy ↓, pin within stopping rule each step', () => {
    const { vertices, edges, alpha, beta, epsilon } = loadFixture('crossing');
    const disjointPairs = calculateDisjointPairs(edges);
    const target: Vec3 = [vertices[0][0], vertices[0][1], vertices[0][2]];
    const set: ConstraintSet = [pointBlock(0, target)];
    const opts = { mode: 'analytical' as const, alpha, beta, epsilon };

    let current = vertices;
    let previousEnergy = calculateEnergy(current, edges, disjointPairs, alpha, beta, epsilon);
    for (let step = 0; step < 3; step++) {
        const r = sobolevStepSet(current, edges, disjointPairs, set, opts);
        expect(r.accepted).toBe(true);
        expect(r.energy).toBeLessThan(previousEnergy);
        current = r.vertices;
        previousEnergy = r.energy;
        const pinDist = distTo(current[0], target);
        const bound = pointRuleBound(current, target);
        console.log(
            `[flowM2:point] step ${step + 1}: τ = ${r.stats.tau}, E = ${r.energy.toExponential(6)}, ` +
                `‖γ₀ − target‖ = ${pinDist.toExponential(3)} (bound ${bound.toExponential(3)})`,
        );
        expect(pinDist).toBeLessThanOrEqual(bound);
    }
});

// Rank rule, feasible side (spec §5.4.4): pinning a vertex WHOSE OWN edges are
// per-edge length-constrained is generically independent — the composed set
// must still yield an accepted, energy-decreasing step honoring both blocks.
test('rank rule: [edgeLengths, point(0)] on crossing — construction passes, accepted step honors pin and every ℓ_I', () => {
    const { vertices, edges, alpha, beta, epsilon } = loadFixture('crossing');
    const disjointPairs = calculateDisjointPairs(edges);
    const ell0 = edgeLengths(vertices, edges);
    const target: Vec3 = [vertices[0][0], vertices[0][1], vertices[0][2]];
    const set: ConstraintSet = [edgeLengthsBlock(ell0), pointBlock(0, target)];
    assertValidConstraintSet(set);

    const e0 = calculateEnergy(vertices, edges, disjointPairs, alpha, beta, epsilon);
    const r = sobolevStepSet(vertices, edges, disjointPairs, set, {
        mode: 'analytical',
        alpha,
        beta,
        epsilon,
    });
    console.log(
        `[flowM2:pin+edges] τ = ${r.stats.tau}, E ${e0.toExponential(6)} → ${r.energy.toExponential(6)}, ` +
            `pin dist = ${distTo(r.vertices[0], target).toExponential(3)}, ` +
            `max per-edge drift = ${maxEdgeDrift(r.vertices, edges, ell0).toExponential(3)}`,
    );
    expect(r.accepted).toBe(true);
    expect(r.energy).toBeLessThan(e0);
    expect(distTo(r.vertices[0], target)).toBeLessThanOrEqual(pointRuleBound(r.vertices, target));
    expect(stackedEdgeDrift(r.vertices, edges, ell0)).toBeLessThanOrEqual(
        edgeLengthsRuleBound(r.vertices, edges),
    );
});
