import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { sobolevStepSet } from '../../src/core/optimizer';
import {
    barycenterBlock,
    type ConstraintSet,
    edgeLengths,
    edgeLengthsBlock,
    pointBlock,
    totalLength,
    totalLengthBlock,
} from '../../src/core/sobolev/constraintSet';
import { barycenterTarget } from '../../src/core/sobolev/constraints';
import { solveConstrainedGradientSetFrozen } from '../../src/core/sobolev/gradient';
import { flatten } from '../../src/core/sobolev/layout';
import { lineSearchStepSet } from '../../src/core/sobolev/lineSearch';
import { calculateDisjointPairs } from '../../src/core/tangentPointEnergy';
import type { Edge, Vec3 } from '../../src/core/testConfigs';

// Frozen-projection factorization reuse (solver-perf Task 6, UN-KILLED
// 2026-07-03 at the reference tolerance): one K(γ₀) = [[Ā, Cᵀ], [C, 0]] LU per
// step serves the gradient solve AND every projection iterate — the authors'
// reference-implementation scheme (ythea/repulsive-curves src/tpe_flow_sc.cpp,
// ProjectGradient + LSBackproject; paper line 734). Goldens generated by
// `tpe_constraints_oracle.py <fixture> <out> <mode> frozen`.
// @see oracle/README.md ("Frozen-projection mode", "Projection tolerance provenance")
// @see docs/superpowers/plans/2026-07-03-sobolev-solver-perf.md (Task 6)

const ARMIJO_C1 = 1e-4;

interface Fixture {
    name: string;
    vertices: Vec3[];
    edges: Edge[];
    alpha: number;
    beta: number;
    epsilon: number;
}

interface GoldenFrozen {
    dE: Vec3[];
    x0_barycenter_target: Vec3;
    L0_total_length_target?: number;
    ell0_edge_length_targets?: number[];
    pin_vertex_index?: number;
    pin_target?: Vec3;
    g_tilde: Vec3[];
    g_tilde_flat: number[];
    lambda: number[];
    conventions: { projection?: string };
    line_search_step: {
        accepted: boolean;
        tau: number;
        energy_before: number;
        energy_after: number;
        slope: number;
        vertices: Vec3[];
        projection_iterations: number;
    };
}

function loadFixture(name: string): Fixture {
    return JSON.parse(
        readFileSync(new URL(`../../oracle/fixtures/${name}.json`, import.meta.url), 'utf8'),
    ) as Fixture;
}

function loadGolden(name: string): GoldenFrozen {
    return JSON.parse(
        readFileSync(new URL(`../../oracle/golden/${name}-frozen.json`, import.meta.url), 'utf8'),
    ) as GoldenFrozen;
}

function euclideanNorm(a: number[]): number {
    let sumSq = 0;
    for (const x of a) sumSq += x * x;
    return Math.sqrt(sumSq);
}

function euclideanDiff(a: number[], b: number[]): number {
    let sumSq = 0;
    for (let i = 0; i < a.length; i++) {
        const d = a[i] - b[i];
        sumSq += d * d;
    }
    return Math.sqrt(sumSq);
}

function distTo(p: Vec3, q: Vec3): number {
    return Math.hypot(p[0] - q[0], p[1] - q[1], p[2] - q[2]);
}

// Drift bounds mirror the per-block projection stopping rule ‖Φ_b‖₂ ≤
// 1e-4·scale_b (reference backproj_threshold into the spec §3.3 rule) — same
// helpers as constraintSetM2Flow.test.ts.
// @see oracle/README.md ("Projection tolerance provenance")
function stackedEdgeDrift(current: Vec3[], edges: Edge[], ell0: number[]): number {
    const now = edgeLengths(current, edges);
    let sq = 0;
    for (let i = 0; i < now.length; i++) {
        const d = now[i] - ell0[i];
        sq += d * d;
    }
    return Math.sqrt(sq);
}

// The six frozen A/B combos: mode → set builder + post-step drift gate.
const COMBOS: {
    golden: string;
    fixture: string;
    set: (g: GoldenFrozen) => ConstraintSet;
    drift: (v: Vec3[], edges: Edge[], g: GoldenFrozen) => { value: number; bound: number };
}[] = [
    ...(['crossing', 'linked-rings', 'knot'] as const).map((fixture) => ({
        golden: `${fixture}-length`,
        fixture,
        set: (g: GoldenFrozen): ConstraintSet => [
            barycenterBlock(g.x0_barycenter_target),
            totalLengthBlock(g.L0_total_length_target as number),
        ],
        drift: (v: Vec3[], edges: Edge[], g: GoldenFrozen) => {
            const L1 = totalLength(v, edges);
            return {
                value: Math.abs(L1 - (g.L0_total_length_target as number)),
                bound: 1e-4 * Math.max(1, L1),
            };
        },
    })),
    ...(['crossing', 'junction-y'] as const).map((fixture) => ({
        golden: `${fixture}-edgelengths`,
        fixture,
        set: (g: GoldenFrozen): ConstraintSet => [
            barycenterBlock(g.x0_barycenter_target),
            edgeLengthsBlock(g.ell0_edge_length_targets as number[]),
        ],
        drift: (v: Vec3[], edges: Edge[], g: GoldenFrozen) => ({
            value: stackedEdgeDrift(v, edges, g.ell0_edge_length_targets as number[]),
            bound: 1e-4 * Math.max(1, totalLength(v, edges)),
        }),
    })),
    {
        golden: 'crossing-point',
        fixture: 'crossing',
        set: (g: GoldenFrozen): ConstraintSet => [
            barycenterBlock(g.x0_barycenter_target),
            pointBlock(g.pin_vertex_index as number, g.pin_target as Vec3),
        ],
        drift: (v: Vec3[], edges: Edge[], g: GoldenFrozen) => {
            const target = g.pin_target as Vec3;
            let R = 0;
            for (const p of v) R = Math.max(R, distTo(p, target));
            return {
                value: distTo(v[g.pin_vertex_index as number], target),
                bound: 1e-4 * Math.max(1, R),
            };
        },
    },
];

for (const combo of COMBOS) {
    const fixture = loadFixture(combo.fixture);
    const golden = loadGolden(combo.golden);

    test(`frozen: ${combo.golden} — one K(γ₀) LU drives gradient solve + every projection iterate, matches oracle`, () => {
        expect(golden.conventions.projection).toBe('frozen');
        const { vertices, edges, alpha, beta, epsilon } = fixture;
        const disjointPairs = calculateDisjointPairs(edges);
        const set = combo.set(golden);
        const gold = golden.line_search_step;

        // (a) Frozen gradient solve at γ₀ — same numbers as the reassemble
        // solve (one factorization, same system), PLUS the reusable operator.
        const { gTilde, residual, frozen } = solveConstrainedGradientSetFrozen(
            vertices,
            edges,
            disjointPairs,
            alpha,
            beta,
            epsilon,
            golden.dE,
            set,
        );
        const gRelDiff =
            euclideanDiff(flatten(gTilde), golden.g_tilde_flat) /
            euclideanNorm(golden.g_tilde_flat);
        expect(gRelDiff).toBeLessThanOrEqual(1e-9);
        expect(residual).toBeLessThanOrEqual(1e-10);

        // (b) Line search with the SAME frozen operator for every projection
        // iterate of every τ-trial (golden inputs — oracle's dE/g̃ — as in
        // constraintSetFlow.test.ts, decoupling from cross-language FD noise).
        const result = lineSearchStepSet(
            vertices,
            edges,
            disjointPairs,
            alpha,
            beta,
            epsilon,
            golden.dE,
            golden.g_tilde,
            set,
            { projection: { frozen } },
        );

        const energyRelDiff =
            Math.abs(result.energyAfter - gold.energy_after) / Math.abs(gold.energy_after);
        const vertexRelDiff =
            euclideanDiff(flatten(result.vertices), flatten(gold.vertices)) /
            euclideanNorm(flatten(gold.vertices));
        console.log(
            `[frozen] ${combo.golden}: accepted = ${result.accepted}, τ = ${result.tau}, ` +
                `iterations = ${result.projectionIterations}, ` +
                `E → ${result.energyAfter.toExponential(6)} (rel diff ${energyRelDiff.toExponential(3)}), ` +
                `vertices rel diff = ${vertexRelDiff.toExponential(3)}`,
        );

        expect(gold.accepted).toBe(true);
        expect(result.accepted).toBe(gold.accepted);
        // τ and iteration counts EXACT — a mismatch means the frozen
        // accept/reject or quasi-Newton loop diverged from the oracle, not
        // rounding (same rationale as the reassemble golden tests).
        expect(result.tau).toBe(gold.tau);
        expect(result.projectionIterations).toBe(gold.projection_iterations);
        expect(energyRelDiff).toBeLessThanOrEqual(1e-12);
        expect(vertexRelDiff).toBeLessThanOrEqual(1e-9);

        // Armijo re-verified from RETURNED numbers — spec §C step 9.
        expect(result.slope).toBeDefined();
        expect(result.energyAfter).toBeLessThanOrEqual(
            result.energyBefore - ARMIJO_C1 * result.tau * (result.slope as number),
        );

        // Post-step drift within the stopping rule, vs the golden's targets.
        const { value, bound } = combo.drift(result.vertices, edges, golden);
        expect(value).toBeLessThanOrEqual(bound);
    });
}

// Default-mode guard (plan 6.3): `projectionMode` omitted ⇒ bit-identical to
// explicit 'reassemble' — the frozen path must be strictly opt-in; committed
// goldens and every pre-existing test run the old path unchanged.
test('default-mode guard: sobolevStepSet with projectionMode omitted ≡ explicit reassemble, bit-identically', () => {
    const { vertices, edges, alpha, beta, epsilon } = loadFixture('crossing');
    const disjointPairs = calculateDisjointPairs(edges);
    const x0 = barycenterTarget(vertices, edges);
    const L0 = totalLength(vertices, edges);
    const set: ConstraintSet = [barycenterBlock(x0), totalLengthBlock(L0)];

    const omitted = sobolevStepSet(vertices, edges, disjointPairs, set, {
        mode: 'analytical',
        alpha,
        beta,
        epsilon,
    });
    const explicit = sobolevStepSet(vertices, edges, disjointPairs, set, {
        mode: 'analytical',
        alpha,
        beta,
        epsilon,
        projectionMode: 'reassemble',
    });

    expect(omitted.accepted).toBe(true);
    expect(explicit.energy).toBe(omitted.energy);
    expect(flatten(explicit.vertices)).toEqual(flatten(omitted.vertices));
    expect(explicit.stats).toEqual(omitted.stats);
});

// Frozen end-to-end via the optimizer entry point: the step must accept and
// report sane stats (the golden suites above pin exact numbers; this pins the
// sobolevStepSet plumbing — operator built once at γ₀, forwarded through the
// line search).
test('sobolevStepSet projectionMode frozen: accepted step on crossing with barycenter+length', () => {
    const { vertices, edges, alpha, beta, epsilon } = loadFixture('crossing');
    const disjointPairs = calculateDisjointPairs(edges);
    const x0 = barycenterTarget(vertices, edges);
    const L0 = totalLength(vertices, edges);
    const set: ConstraintSet = [barycenterBlock(x0), totalLengthBlock(L0)];

    const r = sobolevStepSet(vertices, edges, disjointPairs, set, {
        mode: 'analytical',
        alpha,
        beta,
        epsilon,
        projectionMode: 'frozen',
    });
    expect(r.accepted).toBe(true);
    expect(r.stats.residual).toBeLessThanOrEqual(1e-10);
    const L1 = totalLength(r.vertices, edges);
    expect(Math.abs(L1 - L0)).toBeLessThanOrEqual(1e-4 * Math.max(1, L1));
});
